### ISSUE TITLE
Add (text) button support

### ISSUE THREAD

**Issue by andrewjswan** [benct/lovelace-multiple-entity-row#233] opened 2022-02-01 19:22 UTC
![image](https://user-images.githubusercontent.com/3609660/152036458-fb37ab65-a9fc-40ef-8717-1891f95c4a81.png)
Status Unknown for button :(

**Comment by circa1665** [comment] 2022-02-04 23:03
@andrewjswan as in?:
<img width="445" alt="Screenshot 2022-02-04 at 23 02 05" src="https://user-images.githubusercontent.com/33236082/152614573-c31b3f7e-0308-45aa-b8ad-73f9ef608300.png">
<img width="665" alt="Screenshot 2022-02-04 at 23 02 14" src="https://user-images.githubusercontent.com/33236082/152614575-c92e5054-8d99-4efd-bd13-8c6bd6d0a814.png">

**Comment by ildar170975** [comment] 2022-02-05 00:13
`button` does not have a state - means that it cannot be used as a toggle button.

**Comment by andrewjswan** [comment] 2022-02-05 11:28
> means that it cannot be used as a toggle button.

But it can be pressed. `push`

> If this is what you mean then I would love to see this feature added!

Yes

**Comment by benct** [comment] 2022-02-15 22:31
A text button like the default button type is not currently supported, but you could add an icon button? I.e:
```
- entity: light.living_room
  type: custom:multiple-entity-row
  entities:
    - icon: mdi:lightbulb-on
      tap_action:
        action: call-service
        service: light.toggle
        service_data:
          entity_id: light.living_room

**Comment by bjeanes** [comment] 2022-02-16 06:41
I'd also like to see `script.*` entities displayed with a `RUN` text button (like `entity` card does already), but further the ability to do as @benct has done but with text instead of icon would be swell!

**Comment by benct** [comment] 2022-02-16 10:30
Duplicate of #172

**Closed by benct** 2022-02-16 10:30 UTC
Labels: duplicate, enhancement
