### ISSUE TITLE
timestamp sensors format

### ISSUE THREAD

**Issue by R5fan** [benct/lovelace-multiple-entity-row#47] opened 2020-02-22 13:25 UTC
Timestamp sensor like a doorbell will show only the long date/time format.
For instance

```
  - entity: sensor.front_door_last_activity   
    type: 'custom:multiple-entity-row'
    name: Doorbell
```
Will output: **2020-02-20T20:02:14+00:00**

Whereas regularly:

```
  - entity: sensor.front_door_last_activity     
    name: Doorbell
```
Will output: **1 day ago**

Is there a way to work around this? I tried with format variable, but it seems to ignore those.

**Comment by benct** [comment] 2020-02-25 14:23
No, timestamps/formatting is not supported yet. Duplicate of #43.

**Closed by benct** 2020-02-25 14:23 UTC
Labels: duplicate
