### ISSUE TITLE
On 4.1.0, states/attributes that are string formatted dates are not being formatted at all

### ISSUE THREAD

**Issue by SaifAqqad** [benct/lovelace-multiple-entity-row#142] opened 2020-11-13 15:48 UTC
So basically, if an entity's state or attribute is a string formatted date like: `2020-11-13 17:38:33`, and I use `format: relative` or any other format type, that string is just returned as is instead of making a new Date object with it.

I think it has to do with [this line](https://github.com/benct/lovelace-multiple-entity-row/blob/c20aa7d5d40fa53d2dcc2b3785e462e98c3c58ba/src/index.js#L135)

**Comment by ildar170975** [comment] 2020-11-13 16:08
I have to confirm the problem.
On my setup:

```
        secondary_info:
          entity: device_tracker.life360_somebody
          name: false
          attribute: last_seen
          format: relative
```
Now it looks like this:
![изображение](https://user-images.githubusercontent.com/71872483/99093359-69564f00-25e3-11eb-90a8-f151d252c10c.png)

**Comment by ktownsend-personal** [comment] 2020-11-13 18:27
I just noticed this problem too. I'm using `format: relative` but the display is `2020-11-17T06:30:00`

**Comment by majdzik84** [comment] 2020-11-13 20:19
Any idea why I'm getting invalid_date?

![image](https://user-images.githubusercontent.com/31352476/99117305-c65b0080-25f5-11eb-865a-a89358a8ee7d.png)



In the standard secondary_info: last_changeed tab works fine.

**Comment by firestrife23** [comment] 2020-11-14 05:12
confirmed

**Comment by Pendora2017** [comment] 2020-11-14 16:43
same

**Comment by benct** [comment] 2020-11-16 00:07
Should be fixed in `v4.1.1`.

**Closed by benct** 2020-11-16 00:07 UTC
Labels: bug

**Comment by ktownsend-personal** [comment] 2020-11-16 02:15
Thanks! Confirmed fixed 👍

**Comment by ildar170975** [comment] 2020-11-16 13:01
Yes, fixed! Thank you very much!
