### ISSUE TITLE
No graph when clicking an entity

### ISSUE THREAD

**Issue by newlund** [benct/lovelace-multiple-entity-row#17] opened 2019-11-04 17:37 UTC
Don't know when it happened. Perhaps since last update of multiple-entity-row or after a HA update but now I don't get the graph when I click on an entity in lovelace.
Known bug?

**Comment by benct** [comment] 2019-11-12 16:15
Duplicate of #16. Please follow or contribute there :)

**Closed by benct** 2019-11-12 16:15 UTC
Labels: duplicate
